/**
 * Phase 4 + Phase 5 (task brief): post-OAuth connection verification, followed
 * by exactly ONE read-only Google Calendar smoke test
 * (GOOGLECALENDAR_EVENTS_LIST only). Runs after a human has completed Google's
 * OAuth consent screen for the TEST account via the link generated by
 * create-oauth-link.ts.
 *
 * This script creates NOTHING: no new auth config, no new OAuth link, no new
 * connected account. It only reads back the exact connected account named on
 * the command line (never discovered/guessed), cross-checks it against the
 * expected TEST tenant binding via tenant-binding.ts's real
 * verifyConnectionOwnership()/buildToolExecuteRequest() functions (the same
 * enforcement path production code would use - not a parallel check), and
 * then executes exactly one read-only tool.
 *
 * Fails closed (exits 1, never calls the read-only tool) if:
 *   - the connected account is not in an active/usable state
 *   - its reported user_id does not exactly match the expected TEST identity
 *   - the auth config's OAuth scope has drifted from exactly calendar.events
 *   - the auth config's execution allowlist has drifted from exactly the 4
 *     approved tool slugs
 *
 * Run: COMPOSIO_API_KEY=... npx tsx scripts/poc/composio-calendar/post-oauth-verify-and-list.ts <connected_account_id>
 */
import {
  TenantComposioConnectionRegistry,
  verifyConnectionOwnership,
  buildToolExecuteRequest,
  type TenantBindingError,
  type TenantComposioConnection,
} from "./tenant-binding.js";

export {};

const BASE_URL = process.env.COMPOSIO_BASE_URL || "https://backend.composio.dev";
const TOOLKIT_SLUG = "googlecalendar";
const TARGET_AUTH_CONFIG_NAME = "syveka-poc-googlecalendar-events-scope-only";
const EXPECTED_SCOPE = "https://www.googleapis.com/auth/calendar.events";
const APPROVED_TOOL_SLUGS = [
  "GOOGLECALENDAR_EVENTS_LIST",
  "GOOGLECALENDAR_CREATE_EVENT",
  "GOOGLECALENDAR_EVENTS_GET",
  "GOOGLECALENDAR_DELETE_EVENT",
] as const;

// TEST-only identity - must match create-oauth-link.ts exactly.
const TEST_ORG_ID = "org-test-poc";
const TEST_USER_ID = "user-test-poc";
const TEST_COMPOSIO_USER_ID = `syveka:${TEST_ORG_ID}:${TEST_USER_ID}`;

// Statuses Composio may report for a completed, usable OAuth2 connection.
// Composio's own docs/SDK use different labels across versions/toolkits;
// treat any of these as "active" and everything else as not-yet-usable.
const ACTIVE_STATUSES = new Set(["ACTIVE", "CONNECTED"]);

function maskSecretShaped(obj: unknown): unknown {
  if (Array.isArray(obj)) return obj.map(maskSecretShaped);
  if (obj && typeof obj === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj as Record<string, unknown>)) {
      out[k] = /key|token|secret|password|credential/i.test(k) ? "[REDACTED]" : maskSecretShaped(v);
    }
    return out;
  }
  return obj;
}

async function callComposio(
  apiKey: string,
  method: "GET" | "POST",
  path: string,
  opts?: { query?: Record<string, string>; body?: unknown },
): Promise<{ status: number; body: unknown }> {
  const url = new URL(path, BASE_URL);
  for (const [k, v] of Object.entries(opts?.query ?? {})) url.searchParams.set(k, v);
  const res = await fetch(url, {
    method,
    headers: {
      "x-api-key": apiKey,
      ...(opts?.body ? { "content-type": "application/json" } : {}),
    },
    body: opts?.body ? JSON.stringify(opts.body) : undefined,
  });
  let parsed: unknown = null;
  try {
    parsed = await res.json();
  } catch {
    // non-JSON response - status is still reported below
  }
  return { status: res.status, body: parsed };
}

function extractScopes(authConfigDetail: Record<string, unknown>): string[] {
  const creds = authConfigDetail.credentials as Record<string, unknown> | undefined;
  const raw = creds?.scopes;
  if (typeof raw === "string") return raw.split(/[,\s]+/).filter(Boolean);
  if (Array.isArray(raw)) return raw.filter((s): s is string => typeof s === "string");
  return [];
}

function extractExecutionAllowlist(authConfigDetail: Record<string, unknown>): string[] {
  const tac = authConfigDetail.tool_access_config as
    { tools_available_for_execution?: string[] } | undefined;
  return tac?.tools_available_for_execution ?? [];
}

async function main(): Promise<void> {
  const apiKey = process.env.COMPOSIO_API_KEY;
  if (!apiKey || apiKey.trim().length === 0) {
    console.error("COMPOSIO_API_KEY is not set - failing closed.");
    process.exitCode = 1;
    return;
  }

  const connectedAccountId = process.argv[2];
  if (!connectedAccountId) {
    console.error(
      "Usage: npx tsx post-oauth-verify-and-list.ts <connected_account_id> - failing closed, no id supplied.",
    );
    process.exitCode = 1;
    return;
  }

  console.log("=== Phase 4: post-OAuth connection verification ===\n");
  console.log(`Connected account under test: ${connectedAccountId}`);
  console.log(`Expected TEST identity: org=${TEST_ORG_ID} user=${TEST_USER_ID}`);
  console.log(`Expected Composio user_id: ${TEST_COMPOSIO_USER_ID}`);

  console.log("\n=== Step 1: read back the exact connected account (by id, never discovered) ===");
  const caResult = await callComposio(
    apiKey,
    "GET",
    `/api/v3.1/connected_accounts/${connectedAccountId}`,
  );
  console.log(`-> HTTP ${caResult.status}`);
  if (caResult.status < 200 || caResult.status >= 300) {
    console.error("FAIL CLOSED: could not read connected account. Stopping - no tool call made.");
    process.exitCode = 1;
    return;
  }
  const ca = caResult.body as Record<string, unknown>;
  console.log(JSON.stringify(maskSecretShaped(ca), null, 2));

  const status = ca.status as string | undefined;
  const reportedUserId = ca.user_id as string | undefined;
  const authConfigId = (ca.auth_config as { id?: string } | undefined)?.id;
  const requestedScopes = (ca.requested_scopes as string[] | undefined) ?? [];

  console.log(`\nstatus: ${status}`);
  console.log(`user_id: ${reportedUserId}`);
  console.log(`auth_config.id: ${authConfigId}`);
  console.log(`requested_scopes: ${JSON.stringify(requestedScopes)}`);

  const statusOk = !!status && ACTIVE_STATUSES.has(status);
  if (!statusOk) {
    console.error(
      `\nFAIL CLOSED: connected account status is "${status}", not one of ${JSON.stringify([...ACTIVE_STATUSES])}. ` +
        "Stopping - no tool call made.",
    );
    process.exitCode = 1;
    return;
  }

  console.log(
    "\n=== Step 2: tenant-binding cross-check (real enforcement code, not a duplicate check) ===",
  );
  const registry = new TenantComposioConnectionRegistry();
  const expectedConn: TenantComposioConnection = {
    organizationId: TEST_ORG_ID,
    userId: TEST_USER_ID,
    provider: "composio",
    toolkitSlug: "googlecalendar",
    composioConnectedAccountId: connectedAccountId,
    composioUserId: TEST_COMPOSIO_USER_ID,
    status: "ACTIVE",
  };
  registry.register(expectedConn);

  try {
    verifyConnectionOwnership(reportedUserId ?? "", expectedConn);
    console.log(
      `PASS: Composio-reported user_id ("${reportedUserId}") exactly matches the expected TEST binding.`,
    );
  } catch (err) {
    console.error(`FAIL CLOSED: ${(err as TenantBindingError).message}`);
    process.exitCode = 1;
    return;
  }

  console.log(
    "\n=== Step 3: re-verify the auth config's OAuth scope + execution allowlist (unchanged) ===",
  );
  const listResult = await callComposio(apiKey, "GET", "/api/v3.1/auth_configs", {
    query: { toolkit_slug: TOOLKIT_SLUG, search: TARGET_AUTH_CONFIG_NAME },
  });
  const listBody = listResult.body as { items?: Array<{ id: string; name: string }> };
  const exactMatches = (listBody.items ?? []).filter((i) => i.name === TARGET_AUTH_CONFIG_NAME);
  if (exactMatches.length !== 1) {
    console.error(
      `FAIL CLOSED: expected exactly 1 auth config named "${TARGET_AUTH_CONFIG_NAME}", found ${exactMatches.length}.`,
    );
    process.exitCode = 1;
    return;
  }
  const resolvedAuthConfigId = exactMatches[0]!.id;
  if (authConfigId && authConfigId !== resolvedAuthConfigId) {
    console.error(
      `FAIL CLOSED: connected account's auth_config.id (${authConfigId}) does not match the approved ` +
        `auth config (${resolvedAuthConfigId}). Refusing to proceed.`,
    );
    process.exitCode = 1;
    return;
  }

  const detailResult = await callComposio(
    apiKey,
    "GET",
    `/api/v3.1/auth_configs/${resolvedAuthConfigId}`,
  );
  const detail = (detailResult.body ?? {}) as Record<string, unknown>;
  const scopes = extractScopes(detail);
  const execution = extractExecutionAllowlist(detail);

  const scopeOk = scopes.length === 1 && scopes[0] === EXPECTED_SCOPE;
  const approvedSet = new Set<string>(APPROVED_TOOL_SLUGS);
  const executionSet = new Set(execution);
  const missing = [...approvedSet].filter((s) => !executionSet.has(s));
  const extra = execution.filter((s) => !approvedSet.has(s));
  const executionOk = missing.length === 0 && extra.length === 0 && execution.length === 4;

  console.log(`scopes: ${JSON.stringify(scopes)} (expected exactly [${EXPECTED_SCOPE}])`);
  console.log(`execution allowlist: ${JSON.stringify(execution)}`);
  console.log(`missing approved tools: ${JSON.stringify(missing)}`);
  console.log(`extra/unapproved tools: ${JSON.stringify(extra)}`);

  if (!scopeOk || !executionOk) {
    console.error(
      `\nFAIL CLOSED: scope/execution boundary drifted (scopeOk=${scopeOk}, executionOk=${executionOk}). ` +
        "Stopping - no tool call made.",
    );
    process.exitCode = 1;
    return;
  }
  console.log("\nPASS: OAuth scope and execution allowlist are both unchanged and exact.");

  console.log(
    "\n=== Step 4: build the tool-execute request through the real enforcement choke point ===",
  );
  // Deliberately include a bogus connected_account_id/user_id in the
  // "agent-supplied" arguments, exactly like tenant-binding.negative-test.ts's
  // malicious-payload case, to prove at runtime (not just in the unit test)
  // that buildToolExecuteRequest() ignores them and only ever uses the
  // server-resolved TEST connection - i.e. no cross-tenant fallback is
  // possible even if this were wired to real agent input.
  const agentSuppliedArguments = {
    connected_account_id: "ca_should_never_be_used",
    user_id: "syveka:org-other-tenant:user-other",
  };
  const executeRequest = buildToolExecuteRequest(
    registry,
    { orgId: TEST_ORG_ID, userId: TEST_USER_ID },
    agentSuppliedArguments,
  );
  console.log(
    `Resolved connected_account_id for execution: ${executeRequest.connected_account_id} ` +
      `(bogus agent-supplied id was discarded: ${JSON.stringify(agentSuppliedArguments.connected_account_id)})`,
  );
  if (executeRequest.connected_account_id !== connectedAccountId) {
    console.error(
      "FAIL CLOSED: resolved connected_account_id does not match the connection under test - refusing to execute.",
    );
    process.exitCode = 1;
    return;
  }

  console.log("\n=== Step 5: ONE read-only tool execution - GOOGLECALENDAR_EVENTS_LIST only ===");
  console.log("No CREATE/UPDATE/DELETE tool will be called by this script.");
  const execResult = await callComposio(
    apiKey,
    "POST",
    "/api/v3.1/tools/execute/GOOGLECALENDAR_EVENTS_LIST",
    {
      body: {
        connected_account_id: executeRequest.connected_account_id,
        // The live API requires entity_id alongside connected_account_id
        // (confirmed by a fresh 400 ActionExecute_ConnectedAccountEntityIdRequired
        // probe) - this is the same TEST_COMPOSIO_USER_ID already verified in
        // Step 1/2 as this connected account's owning identity, never a
        // caller-supplied value.
        entity_id: TEST_COMPOSIO_USER_ID,
        arguments: executeRequest.arguments,
      },
    },
  );
  console.log(`-> HTTP ${execResult.status}`);
  console.log(JSON.stringify(maskSecretShaped(execResult.body), null, 2));

  if (execResult.status < 200 || execResult.status >= 300) {
    console.error("\nRead-only LIST execution FAILED.");
    process.exitCode = 1;
    return;
  }

  console.log(
    "\nPOST-OAUTH READ-ONLY PASS: connected account is active and bound to the expected TEST identity, " +
      "OAuth scope and execution allowlist are unchanged and exact, and GOOGLECALENDAR_EVENTS_LIST executed " +
      "successfully through the tenant-resolved connected account with no cross-tenant fallback.",
  );
  console.log(
    "\nSTOPPING HERE, as instructed: no CREATE, UPDATE, or DELETE tool was called. Waiting for explicit " +
      "human authorization before any mutating Calendar test.",
  );
}

main().catch((err) => {
  console.error("post-oauth-verify-and-list failed:", (err as Error).message);
  process.exitCode = 1;
});
