import type { RegistryEntry } from "../../schemas/index.js";

/**
 * Seed registry data. In this MVP the registry is a static in-memory list;
 * a real deployment would load this from a database or a versioned
 * registry service (see docs/skills-registry.md). Every entry here traces
 * back to an actual review - see docs/skills/SECURITY_REVIEW.md at the
 * Syveka repo root for the Scrapling entry's full writeup. Nothing is
 * listed here as APPROVED without that paper trail existing first.
 */
export const REGISTRY: RegistryEntry[] = [
  {
    id: "local-engineering-test",
    name: "Local test runner",
    capability: "engineering.test",
    provider: "local-test-runner",
    source: "syveka-skills/providers/local-test-runner (first-party)",
    license: "N/A (Syveka-owned)",
    trust_level: "TRUSTED",
    risk_level: "LOW",
    status: "APPROVED",
    supported_agents: ["claude-code", "codex", "gemini-cli"],
    permissions: ["fs:read", "process:spawn:local"],
    network_access: false,
    filesystem_access: true,
    scripts: true,
    hooks: false,
    dependencies: [],
    credential_requirements: [],
    approval_required: false,
    installation_scope: "local",
    last_reviewed: "2026-08-19",
    last_updated: "2026-08-19",
    security_notes:
      "First-party. Executes a fixed command/argv array via execFile (never a shell string), " +
      "so caller-supplied input cannot be interpreted as shell syntax. No network access.",
  },
  {
    id: "local-git-diff",
    name: "Local git diff capture",
    capability: "engineering.diff_capture",
    provider: "git-diff",
    source: "syveka-skills/providers/git-diff (first-party)",
    license: "N/A (Syveka-owned)",
    trust_level: "TRUSTED",
    risk_level: "LOW",
    status: "APPROVED",
    supported_agents: ["claude-code", "codex", "gemini-cli"],
    permissions: ["fs:read"],
    network_access: false,
    filesystem_access: true,
    scripts: true,
    hooks: false,
    dependencies: ["git"],
    credential_requirements: [],
    approval_required: false,
    installation_scope: "local",
    last_reviewed: "2026-08-19",
    last_updated: "2026-08-19",
    security_notes: "First-party. Read-only `git diff`/`git diff --stat`, no writes, no network.",
  },
  {
    id: "local-skill-registry",
    name: "Local skill registry lookup",
    capability: "skill.discovery",
    provider: "skill-registry-lookup",
    source: "syveka-skills/providers/skill-registry-lookup (first-party)",
    license: "N/A (Syveka-owned)",
    trust_level: "TRUSTED",
    risk_level: "LOW",
    status: "APPROVED",
    supported_agents: ["claude-code", "codex", "gemini-cli"],
    permissions: [],
    network_access: false,
    filesystem_access: false,
    scripts: false,
    hooks: false,
    dependencies: [],
    credential_requirements: [],
    approval_required: false,
    installation_scope: "local",
    last_reviewed: "2026-08-19",
    last_updated: "2026-08-19",
    security_notes:
      "Searches only this in-memory registry - not a live web/GitHub search. Discovery scope " +
      "is limited to what Syveka has actually reviewed; see docs/architecture.md.",
  },
  {
    id: "scrapling",
    name: "Scrapling",
    capability: "research.web.fetch",
    provider: "scrapling",
    version: "0.4.14",
    commit: "5d213a2d4764002bfc4fed33c32fe09fa8b0bf7f",
    source: "https://github.com/D4Vinci/Scrapling",
    license: "BSD-3-Clause",
    trust_level: "CONDITIONAL",
    risk_level: "MEDIUM",
    status: "APPROVED",
    supported_agents: ["claude-code", "codex", "gemini-cli"],
    permissions: ["network:egress"],
    network_access: true,
    filesystem_access: false,
    scripts: true,
    hooks: false,
    dependencies: ["lxml", "curl_cffi", "playwright"],
    credential_requirements: [],
    approval_required: true,
    installation_scope: "container",
    last_reviewed: "2026-08-19",
    last_updated: "2026-08-19",
    security_notes:
      "PASS WITH CONDITIONS. Built-in SSRF protection covers the HTTP engine only, " +
      "not the browser-based fetch tools. Not installed anywhere - reviewed only. " +
      "See docs/skills/SECURITY_REVIEW.md for the full writeup.",
  },
  {
    id: "shadcn-mcp",
    name: "shadcn/ui MCP",
    capability: "ui.component.provide",
    provider: "shadcn",
    source: "https://ui.shadcn.com",
    license: "MIT",
    trust_level: "TRUSTED",
    risk_level: "LOW",
    status: "REVIEW",
    supported_agents: ["claude-code", "codex", "gemini-cli"],
    permissions: ["network:egress"],
    network_access: true,
    filesystem_access: false,
    scripts: false,
    hooks: false,
    dependencies: [],
    credential_requirements: [],
    approval_required: false,
    installation_scope: "none",
    last_reviewed: "2026-08-19",
    last_updated: "2026-08-19",
    security_notes:
      "Not independently security-reviewed in this MVP; no live MCP connection " +
      "configured in this environment. Provider reports UNAVAILABLE honestly " +
      "rather than being installed on the strength of reputation alone.",
  },
  {
    id: "twentyfirst-dev",
    name: "21st.dev",
    capability: "ui.component.discover",
    provider: "21st-dev",
    source: "https://21st.dev",
    license: "unknown",
    trust_level: "UNTRUSTED",
    risk_level: "MEDIUM",
    status: "REVIEW",
    supported_agents: ["claude-code"],
    permissions: ["network:egress"],
    network_access: true,
    filesystem_access: false,
    scripts: false,
    hooks: false,
    dependencies: [],
    credential_requirements: ["api_key"],
    approval_required: true,
    installation_scope: "none",
    last_reviewed: "2026-08-19",
    last_updated: "2026-08-19",
    security_notes:
      "Metered/remote-generation service - not reviewed or connected. Requires " +
      "owner approval before any live use per the original integration brief.",
  },
  {
    id: "claude-video",
    name: "claude-video (bradautomates/claude-video)",
    capability: "video.analyze",
    provider: "claude-video",
    source: "https://github.com/bradautomates/claude-video",
    license: "unknown",
    trust_level: "UNTRUSTED",
    risk_level: "MEDIUM",
    status: "REVIEW",
    supported_agents: ["claude-code"],
    permissions: ["network:egress", "filesystem:write"],
    network_access: true,
    filesystem_access: true,
    scripts: true,
    hooks: false,
    dependencies: ["yt-dlp", "ffmpeg"],
    credential_requirements: [],
    approval_required: true,
    installation_scope: "none",
    last_reviewed: "2026-08-19",
    last_updated: "2026-08-19",
    security_notes:
      "Not yet independently reviewed (Phase 2F of the original Skills Lab bootstrap " +
      "was never completed - see docs/skills/SKILLS_REGISTRY.md). Not installed.",
  },
];
